### ISSUE TITLE
Wrong description for rule "react/jsx-no-undef"

### ISSUE THREAD

**Issue by rodgracas** [feedzai/eslint-config-feedzai#19]
The description for rule **"react/jsx-no-undef"** is currently: https://github.com/feedzai/eslint-config-feedzai/blob/a43a1079d1b6f27ac80ea48aa277685a70e7d7fe/eslint-config-feedzai-react/rules/react.js#L73 which is the same as **"react/jsx-no-duplicate-props"** rule.

I would recommend changing to something like **"Prevent undeclared variables in JSX"**

**Comment by jcdesousa** [comment]
Can you create the pull requests? thanks

**Comment by rodgracas** [comment]
Sure! I've added you as reviewer :+1:
